import java.io.*;
public class ExcepTest 
{

	public static void main(String[] args) 
	{
		// TODO Auto-generated method stub
		int a[] = new int[2];
	      try 
	      {
	    	  
	         System.out.println("Access element three :" + a[3]);
	         
	      } 
	      
	      catch (ArrayIndexOutOfBoundsException e) 
	      {
	    	  
	         System.out.println("Exception thrown :" + e);
	         
	      }
	      
	      finally 
	      {
	    	  
	         a[0] = 6;
	         System.out.println("First element value: " + a[0]);
	         System.out.println("The finally statement is executed");
	         
	      }

	}

}


output:-

Index 3 out of bounds for length 2
First element value: 6
The finally statement is executed
